const version = require('../package.json');
console.log("|-----------------------------------------------|");
console.log("|   _____            _     _                    |");
console.log("|  |  __ \\          | |   (_)                   |");
console.log("|  | |  | | __ _ ___| |__  _ _   _ _ __ ___     |");
console.log("|  | |  | |/ _\\` / __| '_ \\| | | | | '_ \` _ \\   |"); 
console.log("|  | |__| | (_| \\__ \\ | | | | |_| | | | | | |   |");
console.log("|  |_____/ \\__,_|___/_| |_|_|\\__,_|_| |_| |_|   |");
console.log("|-----------------------------------------------|");
console.log(`|    Version: ${version.version}                             |`);
console.log("|    Installation finish !                      |");
console.log("|    enjoy ;)                                   |");
console.log("|    © Tai Studio 2021/2023                     |");
console.log("|-----------------------------------------------|");
console.log(" ");
console.log("Starting ...");